# fly.toml app configuration file generated for megamishop-minio on 2023-06-19T20:27:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "megamishop-minio"
primary_region = "gdl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
source="miniodata"
destination="/data"

[[services]]
  http_checks = []
  internal_port = 9000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

