# fly.toml app configuration file generated for megamishop-minio on 2023-06-19T20:27:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "megamishop-minio"
primary_region = "gdl"

[http_service]
  internal_port = 9000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
source="miniodata"
destination="/data"

[[services]]
